In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt

In [15]:
df=pd.read_excel('df.xlsx')

#df->df1a
df1a = df.copy()

#scaled
min_age = df1a["Age"].min()
max_age = df1a["Age"].max()

df1a["Scaled_Age"] = (df1a["Age"] - min_age) / (max_age - min_age)

#preview
df1a.head()

c:\Users\lucca\OneDrive\Documents\BBUS\BISM\BISM3206\BISM3206\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

   Gender  Age Payment Method  Churn  LastTransaction  Scaled_Age
0    male   64    credit card  loyal               98    0.635135
1    male   35         cheque  churn              118    0.243243
2  female   25    credit card  loyal              107    0.108108
3  female   39    credit card    NaN              177    0.297297
4    male   39    credit card  loyal               90    0.297297

In [16]:
#df1a
avg_age = df1a["Age"].mean()

#loop comparo
age_comp = []

for age in df1a["Age"]:
    if age > avg_age:
        age_comp.append("Higher")
    elif age < avg_age:
        age_comp.append("Lower")
    else:
        age_comp.append("Same")

df1a["Age_Comparison"] = age_comp

# preview
df1a[["Age", "Age_Comparison"]].head()

   Age Age_Comparison
0   64         Higher
1   35          Lower
2   25          Lower
3   39          Lower
4   39          Lower

In [17]:
df_quiz = df1a.loc[100:500, ["Age", "Scaled_Age", "Age_Comparison"]].reset_index(drop=True)
print(df_quiz)

     Age  Scaled_Age Age_Comparison
0     71    0.729730         Higher
1     79    0.837838         Higher
2     51    0.459459         Higher
3     72    0.743243         Higher
4     61    0.594595         Higher
..   ...         ...            ...
396   69    0.702703         Higher
397   55    0.513514         Higher
398   27    0.135135          Lower
399   25    0.108108          Lower
400   38    0.283784          Lower

[401 rows x 3 columns]

In [ ]:
q1 = df_quiz.loc[100:200, "Age"].mean()
print(q1)

q2 = df_quiz.loc[99:299, "Age"].sum()
print(q2)

46.15841584158416
9161

In [ ]:
#prac 4
df1b = df.copy()

min_age = df1b["Age"].min()
max_age = df1b["Age"].max()

df1b["Scaled_Age"] = [(age - min_age) / (max_age - min_age) for age in df1b["Age"]]

#prev
df1b.head()

   Age Age_Comparison
0   64         Higher
1   35          Lower
2   25          Lower
3   39          Lower
4   39          Lower

In [22]:

#prac 5 lambda
avg_age = df1b["Age"].mean()
df1b["Age_Comparison"] = df1b["Age"].apply(lambda x: "Higher" if x > avg_age else "Lower")

#prev
df1b[["Age", "Age_Comparison"]].head()

   Age Age_Comparison
0   64         Higher
1   35          Lower
2   25          Lower
3   39          Lower
4   39          Lower

In [29]:
# Practice 6: use iloc (based on df1b) and store in df_advanced
cols = df1b.columns.get_indexer(["Age", "Scaled_Age", "Age_Comparison"])
df_advanced = df1b.iloc[100:501, cols].reset_index(drop=True)

#prev
df_advanced.head()
#df_advanced.shape

   Age  Scaled_Age Age_Comparison
0   71    0.729730         Higher
1   79    0.837838         Higher
2   51    0.459459         Higher
3   72    0.743243         Higher
4   61    0.594595         Higher

In [33]:
#prac 7
df1c = df.copy() #into df1c

# Func scaled age and
def add_scaled_age_lc(input_df):
    out = input_df.copy()
    min_age = out["Age"].min()
    max_age = out["Age"].max()
    out["Scaled_Age"] = [(age -min_age) / (max_age -min_age) for age in out["Age"]]
    return out

#age comparo
def add_age_comparison_lambda(input_df):
    out = input_df.copy()
    avg_age = out["Age"].mean()
    out["Age_Comparison"] = out["Age"].apply(lambda x: "Higher" if x > avg_age else "Lower")
    return out

#iloc and reset
def build_advanced_iloc(input_df):
    cols = input_df.columns.get_indexer(["Age", "Scaled_Age", "Age_Comparison"])
    out = input_df.iloc[100:501, cols].reset_index(drop=True)  # 100 to 500 inclusive
    return out

print(add_scaled_age_lc(df1c))
print(add_age_comparison_lambda(step1))
print(build_advanced_iloc(step2))

     Gender  Age Payment Method  Churn  LastTransaction  Scaled_Age
0      male   64    credit card  loyal               98    0.635135
1      male   35         cheque  churn              118    0.243243
2    female   25    credit card  loyal              107    0.108108
3    female   39    credit card    NaN              177    0.297297
4      male   39    credit card  loyal               90    0.297297
..      ...  ...            ...    ...              ...         ...
991  female   29    credit card  loyal               33    0.162162
992    male   84    credit card  loyal              124    0.905405
993    male   20    credit card    NaN               60    0.040541
994    male   19    credit card  loyal               49    0.027027
995  female   24    credit card  loyal               25    0.094595

[996 rows x 6 columns]
     Gender  Age Payment Method  Churn  LastTransaction  Scaled_Age  \
0      male   64    credit card  loyal               98    0.635135
1      male   35         cheque  churn              118    0.243243
2    female   25    credit card  loyal              107    0.108108
3    female   39    credit card    NaN              177    0.297297
4      male   39    credit card  loyal               90    0.297297
..      ...  ...            ...    ...              ...         ...
991  female   29    credit card  loyal               33    0.162162
992    male   84    credit card  loyal              124    0.905405
993    male   20    credit card    NaN               60    0.040541
994    male   19    credit card  loyal               49    0.027027
995  female   24    credit card  loyal               25    0.094595

    Age_Comparison
0           Higher
1            Lower
2            Lower
3            Lower
4            Lower
..             ...
991          Lower
992         Higher
993          Lower
994          Lower
995          Lower

[996 rows x 7 columns]
     Age  Scaled_Age Age_Comparison
0     71    0.729730         Higher
1     79    0.837838         Higher
2     51    0.459459         Higher
3     72    0.743243         Higher
4     61    0.594595         Higher
..   ...         ...            ...
396   69    0.702703         Higher
397   55    0.513514         Higher
398   27    0.135135          Lower
399   25    0.108108          Lower
400   38    0.283784          Lower

[401 rows x 3 columns]